=== Sociolegal-Lab/SC_lab_website/schemas/leader.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Leader",
  "type": "object",
  "properties": {
    "motto": { "type": ["string", "null"] },
    "research_interests": { "type": ["string", "null"] },
    "bio": { "type": ["string", "null"] },
    "education": {
      "type": "array",
      "items": { "type": ["string","null"]}
    },
    "fellowships_and_awards": {
      "type": "array",
      "items": { "type": ["string", "null"] }
    },
    "publication": {
      "type": "array",
      "items": { "type": ["string", "null"] }
    },
    "international_conference": {
      "type": "array",
      "items": { "type": ["string", "null"] }
    }
  },
  "required": ["bio", "motto", "research_interests", "education", "fellowships_and_awards", "publication", "international_conference"]
}

=== Sociolegal-Lab/SC_lab_website/src/data/leader/leader.json
{
    "motto": null,
    "research_interests": "AI and Law; Legal Natural Language Processing; Empirical Legal Studies; AI Governance; Constitutional Law",
    "bio": null,
    "education":[
        "University of California Berkeley School of Law (J.S.D.)",
        "Yale Law School (LL.M.)",
        "National Taiwan University College of Law (LL.B., LL.M.)"
    ],
    "fellowships_and_awards":[
        "Ministry of Technology TOP Grants",
        "UC Berkeley Dr. and Mrs. James C.Y. Soong Fellowship"
    ],
    "publication":[
        null,
        null,
        null
    ],
    "international_conference":[
        null,
        null,
        null
    ]
}
