=== Sociolegal-Lab/SC_lab_website/schemas/member.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Members",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "Chinese_name": { "type": "string" },
      "English_name": { "type": "string" },
      "title": { "type": "string" },
      "research_interests": { "type": "string" },
      "academic_background": { "type": "string" },
      "email": { "type": ["string", "null"] },
      "links": {
        "type": "array",
        "items": { "type": ["string", "null"] }
      },
      "short_bio": { "type": ["string", "null"]}
    },
    "required": ["id", "Chinese_name", "English_name", "title", "research_interests", "academic_background", "email", "links", "short_bio"]
  }
}

=== Sociolegal-Lab/SC_lab_website/src/data/members/members.json
[
    {"id":"1", 
    "Chinese_name":"黃鈞喆", 
    "English_name":"Chun-Che, Huang", 
    "title": "HarryHuang", 
    "research_interests": "Applying AI to legal texts through NLP, RAG, and knowledge modeling, enhancing legal information accessibility.",
    "academic_background": "First-year Master’s student",
    "email": "harryhuang1101@gmail.com",
    "links":[
        null,
        null,
        null
    ],
    "short_bio": "I am a Mathematics graduate from National Cheng Kung University with a strong focus on applying AI to legal text analysis. My research combines NLP, retrieval-augmented generation (RAG), and hierarchical knowledge modeling to enhance entity extraction, constitutional issue identification, and legal knowledge graph construction"
    },
    {"id":"2", 
    "Chinese_name":"周穆可", 
    "English_name":"Mu-Ko, Chou", 
    "title": "Master’s student", 
    "research_interests": "AI ethics and the integration of diverse artificial intelligence technologies",
    "academic_background": "First-year Master’s student",
    "email": "nm6144012@gs.ncku.edu.tw",
    "links":[
        "https://github.com/claire891018",
        "https://www.linkedin.com/in/mu-ko-chou",
        null
    ],
    "short_bio": "Mu-Ko Chou is a master's student in the Intelligent Technology Systems Program at the Miin Wu School of Computing, National Cheng Kung University (NCKU), with a background in political science. Her research focuses on AI ethics and the integration of diverse artificial intelligence technologies, particularly in: (1) legal AI applications; (2) incorporating cultural dimensions into LLMs to examine cross-cultural differences in simulated human decision-making; and (3) designing domain-specific LLM benchmarks with stakeholder participation to ensure local relevance, fairness, and practical value."
    },
    {"id":"3", 
    "Chinese_name":"侯欽祐", 
    "English_name":"Chin-Yu, Hou", 
    "title": "Multidisciplinary Humanities Explorer", 
    "research_interests": "Digital Humanities",
    "academic_background": "Senior undergraduate student",
    "email": "b34111135@gs.ncku.edu.tw",
    "links":[
        null,
        null,
        null
    ],
    "short_bio": "I am a senior undergraduate in History at NCKU, focusing on Digital Humanities. My interests include applying AI, especially language models and retrieval techniques, to expand research possibilities."
    }
]
